language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install pyglet"
install: "pip install coverage"
# command to run tests
script: coverage run test/test.py
script: coverage html